import { Product } from '../_models/product';

export const products: Product[] = [
    {
        id: 1,
        productName: 'Adidas Originals LXCON',
        // tslint:disable-next-line:max-line-length
        productImage: 'https://static.highsnobiety.com/thumbor/foutDBgRoNnM04IQY8O_RNL972Y=/fit-in/1200x800/smart/static.highsnobiety.com/wp-content/uploads/2019/02/19153143/best-adidas-sneakers-2019-main.jpg',
        quantity: 2,
        categoryId: 1,
    },
    {
        id: 2,
        productName: 'Overkill x adidas Consortium ZX 10,000C',
        // tslint:disable-next-line:max-line-length
        productImage: 'https://static.highsnobiety.com/thumbor/L_nmV-lz-WTS6lyO9ehx8PNRNL8=/fit-in/1200x800/smart/static.highsnobiety.com/wp-content/uploads/2019/02/18172053/best-adidas-sneakers-2019-03.jpg',
        quantity: 2,
        categoryId: 1,
    },
    {
        id: 3,
        productName: 'Adidas Running Ultra Boost 19',
        productImage: 'https://static.highsnobiety.com/thumbor/VwdrpahXw6Bs0U8PHFPpO11j7Nc=/fit-in/1200x800/smart/static.highsnobiety.com/wp-content/uploads/2019/02/18171944/best-adidas-sneakers-2019-02.jpg',
        quantity: 2,
        categoryId: 1,
    },
    {
        id: 4,
        productName: 'Adidas Original Men’s NMD_xr1 PK Shoes For Men',
        productImage: 'https://www.gearhungry.com/wp-content/uploads/bfi_thumb/adidas-original-men’s-nmd_xr1-pk-sneaker-6qymgn4fgi4k018lpj6f4pbu0kky61mcup6t2vtc2ku.jpg',
        quantity: 1,
        categoryId: 1,
    },
    {
        id: 5,
        productName: 'Adidas Men’s Ultraboost Ltd Running Shoes For Men',
        productImage: 'https://www.gearhungry.com/wp-content/uploads/bfi_thumb/adidas-men’s-ultraboost-ltd-running-shoe-6qymgn4fgi4k018lpj6f4pbu0kky61mcup6t2vtc2ku.jpg',
        quantity: 5,
        categoryId: 1,
    },
    {
        id: 6,
        productName: 'Nike Air Presto',
        productImage: 'https://www.gearhungry.com/wp-content/uploads/bfi_thumb/nike-air-presto-essential-shoes-6qymgkifliozbs8e8s1sfrzjx61tgnvzp09kiw57fv2.jpg',
        quantity: 5,
        categoryId: 2,
    },
    {
        id: 7,
        productName: 'Nike Air Force 1 Low',
        productImage: 'https://cdn.runrepeat.com/i/nike/24841/nike-mens-air-force-low-1-basketball-shoe-white-white-9-mens-white-white-7dc1-380.jpg',
        quantity: 10,
        categoryId: 2,
    },
    {
        id: 8,
        productName: 'Nike Air Max Motion 2',
        productImage: 'https://cdn.runrepeat.com/i/nike/31347/nike-air-max-motion-2-scarpe-da-ginnastica-basse-uomo-nero-black-white-012-44-eu-nero-black-white-012-6b85-380.jpg',
        quantity: 2,
        categoryId: 2,
    },
    {
        id: 9,
        productName: 'Nike Air Huarache',
        productImage: 'https://cdn.runrepeat.com/i/nike/24846/nike-air-huarache-zapatillas-de-deporte-para-hombre-blanco-plateado-white-white-pure-platinum-38-5-eu-hombre-blanco-plateado-white-white-pure-platinum-bea3-380.jpg',
        quantity: 2,
        categoryId: 2,
    },
    {
        id: 10,
        productName: 'MLB Unisex NY New York Yankees Chunky Dad',
        productImage: 'https://media.karousell.com/media/photos/products/2019/07/22/mlb_unisex_ny_new_york_yankees_chunky_dad_shoes_size_245__us_75__uk_5__eur_385_125_1563778787_04a5402d_progressive.jpg',
        quantity: 5,
        categoryId: 3,
    },
    {
        id: 11,
        productName: 'MLB Boston',
        productImage: 'https://media.karousell.com/media/photos/products/2020/02/07/mlb_bostonif_interest_pls_pm_1581051783_78bcf0c5_progressive.jpg',
        quantity: 1,
        categoryId: 3,
    },
    {
        id: 12,
        productName: 'MLB La Dodger',
        productImage: 'https://product.hstatic.net/1000296292/product/1_0128b6c9-f938-4a91-9e79-2d825518778c_df3c0a775c3e48ad98d1bbd49f0add05_master.jpg',
        quantity: 0,
        categoryId: 3,
    },
    {
        id: 13,
        productName: 'Converse Chuck Taylor All Star Core Ox ',
        productImage: 'https://www.gearhungry.com/wp-content/uploads/bfi_thumb/converse-chuck-taylor-all-star-core-ox-6qymgpqfbhk4oa8t6ab1tmo43z42vfcq0e41mvhgpam.jpg',
        quantity: 2,
        categoryId: 4,
    },
    {
        id: 14,
        productName: '2_Converse_Chuck_Taylor_All_Star_Canvas_High_Top_Sneaker',
        productImage: 'https://www.gearhungry.com/wp-content/uploads/bfi_thumb/converse-chuck-taylor-all-star-canvas-high-top-sneaker-6qymgpqfbhk4oa8t6ab1tmo43z42vfcq0e41mvhgpam.jpg',
        quantity: 6,
        categoryId: 4,
    },
    {
        id: 15,
        productName: 'Converse Unisex Chuck Taylor All Star Sneaker',
        productImage: 'https://www.gearhungry.com/wp-content/uploads/bfi_thumb/converse-unisex-chuck-taylor-all-star-sneaker-6qymgpqfbhk4oa8t6ab1tmo43z42vfcq0e41mvhgpam.jpg',
        quantity: 2,
        categoryId: 4,
    },
    {
        id: 16,
        productName: 'Converse Chuck Taylor All Star Leather Ox ',
        productImage: 'https://www.gearhungry.com/wp-content/uploads/bfi_thumb/converse-womens-chuck-taylor-all-star-leather-ox-6qymgpqfbhk4oa8t6ab1tmo43z42vfcq0e41mvhgpam.jpg',
        quantity: 2,
        categoryId: 4,
    },
    {
        id: 17,
        // tslint:disable-next-line:quotemark
        productName: "Converse Men's Street Canvas Mid Top Sneaker",
        productImage: 'https://www.gearhungry.com/wp-content/uploads/bfi_thumb/converse-mens-street-canvas-mid-top-sneaker-6qymgpqfbhk4oa8t6ab1tmo43z42vfcq0e41mvhgpam.jpg',
        quantity: 2,
        categoryId: 4,
    },
    {
        id: 18,
        productName: 'Converse Unisex Chuck Taylor Leather Top Sneakers ',
        productImage: 'https://www.gearhungry.com/wp-content/uploads/bfi_thumb/converse-unisex-chuck-taylor-leather-top-sneakers-6qymgpqfbhk4oa8t6ab1tmo43z42vfcq0e41mvhgpam.jpg',
        quantity: 2,
        categoryId: 4,
    },
    {
        id: 19,
        productName: 'Vans Authentic Core Classic Sneakers',
        productImage: 'https://cdn.nhanh.vn/cdn/store/10103/artCT/58518/top_10_doi_giay_vans_hot_nhat_2019_2.jpg',
        quantity: 2,
        categoryId: 5,
    },
    {
        id:20,
        productName: 'Vans Sk8-Hi Casual High-Top Skate Shoes',
        productImage: 'https://cdn.nhanh.vn/cdn/store/10103/artCT/58518/top_10_doi_giay_vans_hot_nhat_2019_3.jpg',
        quantity: 2,
        categoryId: 5,
    },
    {
        id: 21,
        productName: 'Vans Classic Checkerboard Slip-on',
        productImage: 'https://cdn.nhanh.vn/cdn/store/10103/artCT/58518/top_10_doi_giay_vans_hot_nhat_2019_1.jpg',
        quantity: 2,
        categoryId: 5,
    },
    {
        id: 22,
        productName: 'Vans Sk8-Mid Skate Shoes',
        productImage: 'https://cdn.nhanh.vn/cdn/store/10103/artCT/58518/top_10_doi_giay_vans_hot_nhat_2019_10.jpg',
        quantity: 2,
        categoryId: 5,
    },
    {
        id: 23,
        productName: 'Vans Old Skoll Low-top Trainers',
        productImage: 'https://cdn.nhanh.vn/cdn/store/10103/artCT/58518/top_10_doi_giay_vans_hot_nhat_2019_6.jpg',
        quantity: 2,
        categoryId: 5,
    },
    {
        id: 24,
        productName: 'PUMA RS-X Toys sneakers',
        productImage: 'https://cdn-images.farfetch-contents.com/14/14/72/70/14147270_18767491_1000.jpg',
        quantity: 2,
        categoryId: 6,
    },
    {
        id: 25,
        productName: 'PUMA Disc Blaze Treasure sneakers',
        productImage: 'https://cdn-images.farfetch-contents.com/14/10/64/37/14106437_18620450_1000.jpg',
        quantity: 2,
        categoryId: 6,
    }
];
